INSERT INTO branch_science VALUES (2, 'Mathematics');
INSERT INTO branch_science VALUES (1, 'Mechanical Engineering');
INSERT INTO branch_science VALUES (3, 'Computer and information sciences');
INSERT INTO branch_science VALUES (4, 'Physical sciences');
INSERT INTO branch_science VALUES (5, 'Chemical sciences');
INSERT INTO branch_science VALUES (6, 'Biological sciences');
INSERT INTO branch_science VALUES (7, 'Health sciences');
INSERT INTO branch_science VALUES (8, 'Basic medicine');
INSERT INTO branch_science VALUES (9, 'Earth and related Environmental sciences');
INSERT INTO branch_science VALUES (10, 'Social sciences');
INSERT INTO branch_science VALUES (11, 'Humanities');