INSERT INTO subject_science(id, name, branch_id) VALUES (1,'Nano-Technology',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (2,'4D Printing',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (3,'Artificial General intelligence',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (4,'Deep Reinforcement Learning',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (5,'Neuromorphic Hardware',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (6,'Human Augmentation',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (7,'5G',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (8,'Serverless PaaS',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (9,'Digital Twin',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (10,'Quantum Computing',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (11,'Volumetric Displays',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (12,'Brain-Computer Interface',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (13,'Conversational User Interface',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (14,'Smart Workplace',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (15,'Augmented Data Discovery',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (16,'Edge Computing',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (17,'Smart Robots',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (18,'Internet of Things',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (19,'Virtual Assistants',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (20,'Connected Home',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (21,'Deep Learning',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (22,'Machine Learning',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (23,'Autonomous Vehicles',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (24,'Nanotube Electronics',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (25,'Cognitive Computing',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (26,'Blockchain',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (27,'Commercial UAVs',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (28,'Cognitive Expert Advisors',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (29,'Enterprise Taxonomy and Ontology Management',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (30,'Software-Defined Security',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (31,'Augmented Reality',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (32,'Virtual Reality',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (33,'CNC',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (34,'Lazer',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (35,'3D Printing',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (36,'Energy Solutions',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (37,'CAM Sustainability',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (38,'CAD Sustainability',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (39,'Fuel-Efficient Engine Technologies',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (40,'High-Speed Machining',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (41,'Advances in Gas Turbine Technology',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (42,'Stir Friction Welding',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (43,'Agile Manufacturing',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (44,'Advances in Heating',1);
INSERT INTO subject_science(id, name, branch_id) VALUES (45,'Pure mathematics',2);
INSERT INTO subject_science(id, name, branch_id) VALUES (46,'Applied mathematics',2);
INSERT INTO subject_science(id, name, branch_id) VALUES (47,'Statistics and probability',2);
INSERT INTO subject_science(id, name, branch_id) VALUES (48,'Computer sciences',3);
INSERT INTO subject_science(id, name, branch_id) VALUES (49,'information science',3);
INSERT INTO subject_science(id, name, branch_id) VALUES (50,'bioinformatics',3);
INSERT INTO subject_science(id, name, branch_id) VALUES (51,'Atomic',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (52,'molecular',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (53,'chemical',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (54,'Condensed matter physics',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (55,'Particles and fields physics',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (56,'Nuclear physics',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (57,'Fluids and plasma physics',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (58,'Optics',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (59,'Acoustics',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (60,'Astronomy',4);
INSERT INTO subject_science(id, name, branch_id) VALUES (61,'Organic chemistry',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (62,'Inorganic and nuclear chemistry',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (63,'Physical chemistry',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (64,'Polymer science',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (65,'Electrochemistry',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (66,'Colloid chemistry',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (67,'Analytical chemistry',5);
INSERT INTO subject_science(id, name, branch_id) VALUES (68,'Geosciences',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (69,'Mineralogy',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (70,'Palaeontology',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (71,'Geochemistry',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (72,'geophysics',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (73,'Physical geography',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (74,'Geology',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (75,'Volcanology',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (76,'Environmental',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (77,'Meteorology',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (78,'atmospheric',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (79,'climatic research',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (80,'Oceanography',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (81,'Hydrology',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (82,'Water resources',9);
INSERT INTO subject_science(id, name, branch_id) VALUES (83,'Cell biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (84,'Microbiology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (85,'Virology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (86,'Biochemistry',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (87,'molecular biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (88,'Biochemical research methods',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (89,'Mycology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (90,'Biophysics',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (91,'Genetics and heredity',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (92,'reproductive biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (93,'developmental biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (94,'Plant sciences',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (95,'botany',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (96,'Zoology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (97,'Ornithology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (98,'Entomology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (99,'Behavioural sciences biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (100,'Marine biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (101,'freshwater biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (102,'limnology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (103,'Ecology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (104,'Biodiversity conservation',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (105,'Biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (106,'Evolutionary biology',6);
INSERT INTO subject_science(id, name, branch_id) VALUES (107,'Anatomy and morphology',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (108,'Human genetics',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (109,'Immunology',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (110,'Neurosciences',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (111,'harmacology and pharmacy',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (112,'Medicinal chemistry',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (113,'Toxicology',8);
INSERT INTO subject_science(id, name, branch_id) VALUES (114,'Health care sciences and services',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (115,'Health policy and services',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (116,'Nursing',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (117,'Nutrition',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (118,'Dietetics',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (119,'Public and environmental health',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (120,'Tropical medicine',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (121,'Parasitology',7);
INSERT INTO subject_science(id, name, branch_id) VALUES (122,'Psychology',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (123,'Economics',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (124,'Business and Management',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (125,'Education',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (126,'Sociology',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (127,'Demography',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (128,'Anthropology',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (129,'ethnology',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (130,'criminology',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (131,'Political science',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (132,'Environmental sciences',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (133,'Journalism',10);
INSERT INTO subject_science(id, name, branch_id) VALUES (134,'Library science',10);